### ISSUE TITLE
FLOP/Parameters 계산 방법

### ISSUE THREAD

**Issue by jungae-park** [ddps-lab/edge-management-module#1]
https://github.com/ddps-lab/research-issues/issues/22
iicws 2019 논문에서 FLOPS/Model size (parameter size) 계산한 내용을 살펴보아,  
모든 모델에 대해 계산을 해보고 IPS와 IPS(inf) 차이를 살펴봅니다.

**Comment by jungae-park** [comment]
**1. Characterizing the Deployment of Deep Neural Networks on Commercial Edge Devices 논문의 경우 flop/param 계산**
* 모델의 input size, FLOP (giga), Parameters, FLOP/param
* batch 1 기준으로 계산
![Image](https://user-images.githubusercontent.com/46885199/178174547-91af6d71-9ff3-4562-825f-29b0570e1190.png)

**2. keras-flops 라이브러리를 통해 배치 단위별로 모델이 필요로 하는 연산량 계산**
```
==================Model Analysis Report======================

Doc:
scope: The nodes in the model graph are organized by their names, which is hierarchical like filesystem.
flops: Number of float operations. Note: Please read the implementation for the math behind it.

Profile:
node name | # float_ops
_TFProfRoot (--/1.15b flops)
  mobilenet_1.00_224/conv_pw_10/Conv2D (102.76m/102.76m flops)
  mobilenet_1.00_224/conv_pw_11/Conv2D (102.76m/102.76m flops)
  mobilenet_1.00_224/conv_pw_9/Conv2D (102.76m/102.76m flops)
  mobilenet_1.00_224/conv_pw_8/Conv2D (102.76m/102.76m flops)
  mobilenet_1.00_224/conv_pw_7/Conv2D (102.76m/102.76m flops)
  mobilenet_1.00_224/conv_pw_13/Conv2D (102.76m/102.76m flops)
  mobilenet_1.00_224/conv_pw_5/Conv2D (102.76m/102.76m flops)
  mobilenet_1.00_224/conv_pw_3/Conv2D (102.76m/102.76m flops)
  mobilenet_1.00_224/conv_pw_1/Conv2D (51.38m/51.38m flops)
  mobilenet_1.00_224/conv_pw_12/Conv2D (51.38m/51.38m flops)
  mobilenet_1.00_224/conv_pw_6/Conv2D (51.38m/51.38m flops)
  mobilenet_1.00_224/conv_pw_4/Conv2D (51.38m/51.38m flops)
  mobilenet_1.00_224/conv_pw_2/Conv2D (51.38m/51.38m flops)
  mobilenet_1.00_224/conv1/Conv2D (21.68m/21.68m flops)
  mobilenet_1.00_224/conv_dw_3/depthwise (7.23m/7.23m flops)
  mobilenet_1.00_224/conv_dw_1/depthwise (7.23m/7.23m flops)
  mobilenet_1.00_224/conv_dw_5/depthwise (3.61m/3.61m flops)
  mobilenet_1.00_224/conv_dw_2/depthwise (3.61m/3.61m flops)
  mobilenet_1.00_224/conv_preds/Conv2D (2.05m/2.05m flops)
  mobilenet_1.00_224/conv_dw_4/depthwise (1.81m/1.81m flops)
  mobilenet_1.00_224/conv_dw_7/depthwise (1.81m/1.81m flops)
  mobilenet_1.00_224/conv_dw_8/depthwise (1.81m/1.81m flops)
  mobilenet_1.00_224/conv_dw_9/depthwise (1.81m/1.81m flops)
  mobilenet_1.00_224/conv_dw_11/depthwise (1.81m/1.81m flops)
  mobilenet_1.00_224/conv_dw_10/depthwise (1.81m/1.81m flops)
  mobilenet_1.00_224/conv_pw_1_bn/FusedBatchNormV3 (1.61m/1.61m flops)
  mobilenet_1.00_224/conv_dw_6/depthwise (903.17k/903.17k flops)
  mobilenet_1.00_224/conv_dw_13/depthwise (903.17k/903.17k flops)
  mobilenet_1.00_224/conv_dw_3_bn/FusedBatchNormV3 (803.58k/803.58k flops)
  mobilenet_1.00_224/conv_pw_2_bn/FusedBatchNormV3 (803.58k/803.58k flops)
  mobilenet_1.00_224/conv_pw_3_bn/FusedBatchNormV3 (803.58k/803.58k flops)
  mobilenet_1.00_224/conv1_bn/FusedBatchNormV3 (803.01k/803.01k flops)
  mobilenet_1.00_224/conv_dw_1_bn/FusedBatchNormV3 (803.01k/803.01k flops)
  mobilenet_1.00_224/conv_dw_12/depthwise (451.58k/451.58k flops)
  mobilenet_1.00_224/conv_pw_5_bn/FusedBatchNormV3 (402.94k/402.94k flops)
  mobilenet_1.00_224/conv_dw_5_bn/FusedBatchNormV3 (402.94k/402.94k flops)
  mobilenet_1.00_224/conv_pw_4_bn/FusedBatchNormV3 (402.94k/402.94k flops)
  mobilenet_1.00_224/conv_dw_2_bn/FusedBatchNormV3 (401.79k/401.79k flops)
  mobilenet_1.00_224/conv_pw_10_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_pw_9_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_dw_10_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_pw_8_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_dw_11_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_pw_7_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_pw_6_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_dw_7_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_dw_8_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_dw_9_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_pw_11_bn/FusedBatchNormV3 (203.78k/203.78k flops)
  mobilenet_1.00_224/conv_dw_4_bn/FusedBatchNormV3 (201.47k/201.47k flops)
  mobilenet_1.00_224/conv_dw_13_bn/FusedBatchNormV3 (106.50k/106.50k flops)
  mobilenet_1.00_224/conv_pw_13_bn/FusedBatchNormV3 (106.50k/106.50k flops)
  mobilenet_1.00_224/conv_pw_12_bn/FusedBatchNormV3 (106.50k/106.50k flops)
  mobilenet_1.00_224/conv_dw_6_bn/FusedBatchNormV3 (101.89k/101.89k flops)
  mobilenet_1.00_224/conv_dw_12_bn/FusedBatchNormV3 (53.25k/53.25k flops)
  mobilenet_1.00_224/global_average_pooling2d/Mean (50.18k/50.18k flops)
  mobilenet_1.00_224/predictions/Softmax (5.00k/5.00k flops)
  mobilenet_1.00_224/conv_preds/BiasAdd (1.00k/1.00k flops)

======================End of Report==========================
FLOPS: 1.15 G
```
* 이러한 형태로 layer 마다 연산량을 계산하고 합계를 구해 flop 계산

**3. xavier, tx1, tx2, nano 장비에서 mobilnet v1, v2, inception v3 모델 계산 결과** 
* 같은 장비에서 모델들의 flop 값은 다르며, 다른 장비에서 같은 모델의 flop 값이 같습니다.
[mobilenet v1]
![Image](https://user-images.githubusercontent.com/46885199/178175023-47d59b3d-acd0-4992-bfeb-22e0820930bb.png)
[mobilenet v2]
![Image](https://user-images.githubusercontent.com/46885199/178175098-595d1dbb-d22b-4ec0-8625-c6323d56771b.png)
[inception v3]
![Image](https://user-images.githubusercontent.com/46885199/178175138-d6494cc0-6aee-41f0-9c6b-891214a4bd92.png)

**4. 이슈사항**
* tflite model(coral tpu), yolov5 model에 대해서도 측정을 해보고 있으나, keras-flops 라이브러리가 pb 모델의 경우만 지원하여 에러가 발생합니다.
* 계산 할 수 있는 추가적인 방법을 찾고 있습니다.

**Comment by hyu-leeky** [comment]
정애야. 그런데 "같은 장비에서 모델들의 flop 값은 다르며, 다른 장비에서 같은 모델의 flop 값이 같습니다." 이렇게 이야기를 했는데 아래에 있는 표 3개의 각 행이 어떤걸 의미하는지 모르겠지만 왠지 장비를 의미할것 같은데, Flop 값은 다르게 나오는거 아닌가? 아래 3개 테이블 각 행의 타이틀이 어떻게 되?

**Comment by jungae-park** [comment]
다른 장비에서 같은 모델의 flop값이 같아, 표는 대표로 xavier 장비에서 batch 1-128까지의 값을 계산하였습니다.
행,열 고정으로 시트를 수정해놓겠습니다.

**Comment by hyu-leeky** [comment]
위의 캡쳐된 이미지를 이야기한건데. 시트는 다른데 있나보구나. 일단 위의 캡쳐 이미지에서 각 행은 서로 다른 배치 사이즈를 의미한다고 보면 되는거지?

**Comment by jungae-park** [comment]
네 맞습니다. 각 행은 서로 다른 배치 사이즈를 의미합니다.
시트는 기존 시트에 추가하여 기록하였습니다.
https://docs.google.com/spreadsheets/d/1hhYyZWexZVVmE8NIR5lIlMwPGjTQkHUEFYAR46YJ9tw/edit#gid=1792697168

**Comment by jungae-park** [comment]
* flop/parameter 계산이 필요한 모델
1. edgetpu tflite model
2. yolo v5 model

* 계산 방식
1. 기존 keras-flops 라이브러리를 사용하여 측정을 시도하였지만, keras에서 API로 제공해주는 모델이 아닌 경우 측정이 되지 않는 이슈 발생
2. edgetpu tflite model과 yolo v5 model을 각기 다른 방법으로 측정 시도
* edgetpu tflite model 
https://github.com/lisosia/tflite-flops
위의 github를 참고하여 tflite model의 flops를 측정해보았지만, github에서 예제로 제공해준 tflite model만 측정이 가능하고, 우리가 보유하고 있는 tflite model에 대한 flops 계산이 이루어지지 않아 이유를 좀 더 살펴봐야함

* yolo v5 model
yolo v5 model의 경우, pytorch 모델을 tensorflow 모델로 convert하여 사용한 것
https://github.com/jahongir7174/FLOPS-pt
pytorch yolo v5 model에 대한 flops 계산은 찾았지만, tensorflow yolo v5 model에 대한 계산은 찾지못해 다른 방법으로 아래와 같이 시도

* model_profiler 라이브러리 사용 (yolo v5 - tensorflow model)
https://pypi.org/project/model-profiler/
예제로 vgg16 모델에 대한 flops 계산을 진행하였을 때, 아래와 같은 결과물을 얻을 수 있어 yolo v5 모델로 바꾸어 flops를 계산하였지만 에러가 발생하여 확인 중

> [code]
> ```
> from model_profiler import model_profiler
> import tensorflow as tf
> 
> model_path="./yolov5/yolov5s_saved_model"
> model=tf.saved_model.load(model_path)
> 
> model.summary()
> Batch_size = 128
> profile = model_profiler(model, Batch_size)
> 
> print(profile)
> ```
> [예제 vgg16 model 결과물]
> ```
> | Model Profile                    | Value    | Unit    |
> |----------------------------------|----------|---------|
> | Selected GPUs                    | ['0']    | GPU IDs |
> | No. of FLOPs                     | 0.3093   | BFLOPs  |
> | GPU Memory Requirement           | 7.4067   | GB      |
> | Model Parameters                 | 138.3575 | Million |
> | Memory Required by Model Weights | 527.7921 | MB      |
> ```
> 
> [yolo v5 model 에러]
> ```
> AttributeError: '_UserObject' object has no attribute 'layers'
> ```

**Comment by unhochoi** [comment]
- tensorflow 프레임워크에 사용할 수 있는 keras-flops 라이브러리는 CNN 기반 layer에 대한 계산만 제공
    - [https://pypi.org/project/keras-flops/#:~:text=Not support tf.keras.layers as follows. They are calculated as zero or smaller value than correct value](https://pypi.org/project/keras-flops/#:~:text=Not%20support%20tf.keras.layers%20as%20follows.%20They%20are%20calculated%20as%20zero%20or%20smaller%20value%20than%20correct%20value).

**Comment by jungae-park** [comment]
* edge tflite model or original torch yolov5 model의 경우
keras-flops 라이브러리로 flop 측정시, 시퀀스한 layer 구조별로 계산하여 layer가 그렇게 짜여져 있어야함
keras-flops가 꼭 필요로하는 layer가 포함되어 있지 않거나 인식하지 못하는 layer가 포함되어 있을 것으로 추정하여 다른 방법으로 계산 시도 필요

* edgetpu tflite model flops 계산
https://github.com/lisosia/tflite-flops (batch 단위별 측정 불가능)
tflite 모델의 flop을 계산해주는 github을 참고해보았지만 예제로 제시한 tflite 모델과 yolov5 edgetpu tflite 모델만 계산이 되고, mobilenet v1, v2, inception v3 edgetpu tflite 모델의 flops 계산이 이루어지지 않음
에러 없이 실행은 되지만 아래 결과 처럼 layer 마다 계산 값이 없고, 빈칸으로 출력됨 
**[edgetpu tflite yolo v5 측정 결과 값(batch 1 기준 모델)]**
Total: 5974.0 M FLOPS, 5.974 G FLOPS

> ```
> root@d487bb3d52fe:/edge-inference/CNN/model/yolo_v5_edgetpu_tflite# python3 -m tflite_flops yolov5s-int8_edgetpu.tflite 
> OP_NAME            | M FLOPS
> ------------------------------
> CUSTOM             | <IGNORED>
> RESIZE_NEAREST_NEIGHBOR | <IGNORED>
> CONCATENATION      | <IGNORED>
> CONV_2D            | 209.7
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 52.4
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 471.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 209.7
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONCATENATION      | <IGNORED>
> CONV_2D            | 209.7
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 104.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> QUANTIZE           | <IGNORED>
> RESIZE_NEAREST_NEIGHBOR | <IGNORED>
> CONCATENATION      | <IGNORED>
> CONV_2D            | 209.7
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 52.4
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 471.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 209.7
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONCATENATION      | <IGNORED>
> CONV_2D            | 209.7
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> PAD                | <IGNORED>
> CONV_2D            | 471.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONCATENATION      | <IGNORED>
> CONV_2D            | 104.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 52.4
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 471.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 104.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONCATENATION      | <IGNORED>
> CONV_2D            | 209.7
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> PAD                | <IGNORED>
> CONV_2D            | 471.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONCATENATION      | <IGNORED>
> CONV_2D            | 104.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 52.4
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 471.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 104.9
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONCATENATION      | <IGNORED>
> CONV_2D            | 209.7
> LOGISTIC           | <IGNORED>
> MUL                | <IGNORED>
> CONV_2D            | 104.4
> LOGISTIC           | <IGNORED>
> QUANTIZE           | <IGNORED>
> RESHAPE            | <IGNORED>
> STRIDED_SLICE      | <IGNORED>
> MUL                | <IGNORED>
> ADD                | <IGNORED>
> MUL                | <IGNORED>
> MUL                | <IGNORED>
> STRIDED_SLICE      | <IGNORED>
> MUL                | <IGNORED>
> MUL                | <IGNORED>
> MUL                | <IGNORED>
> STRIDED_SLICE      | <IGNORED>
> CONCATENATION      | <IGNORED>
> RESHAPE            | <IGNORED>
> CONV_2D            | 208.9
> LOGISTIC           | <IGNORED>
> QUANTIZE           | <IGNORED>
> RESHAPE            | <IGNORED>
> STRIDED_SLICE      | <IGNORED>
> MUL                | <IGNORED>
> ADD                | <IGNORED>
> MUL                | <IGNORED>
> MUL                | <IGNORED>
> STRIDED_SLICE      | <IGNORED>
> MUL                | <IGNORED>
> MUL                | <IGNORED>
> MUL                | <IGNORED>
> STRIDED_SLICE      | <IGNORED>
> CONCATENATION      | <IGNORED>
> RESHAPE            | <IGNORED>
> CONV_2D            | 417.8
> LOGISTIC           | <IGNORED>
> QUANTIZE           | <IGNORED>
> RESHAPE            | <IGNORED>
> STRIDED_SLICE      | <IGNORED>
> MUL                | <IGNORED>
> ADD                | <IGNORED>
> MUL                | <IGNORED>
> MUL                | <IGNORED>
> STRIDED_SLICE      | <IGNORED>
> MUL                | <IGNORED>
> MUL                | <IGNORED>
> MUL                | <IGNORED>
> STRIDED_SLICE      | <IGNORED>
> CONCATENATION      | <IGNORED>
> RESHAPE            | <IGNORED>
> CONCATENATION      | <IGNORED>
> QUANTIZE           | <IGNORED>
> ------------------------------
> Total: 5974.0 M FLOPS
> ```
따라서 다른 방법인 flopco-keras를 사용하여 측정 시도 중
https://github.com/evgps/flopco-keras 

* yolo v5 model (TF-FP32) flops 계산
yolo v5 github의 torch_utils 코드에 torch 모델에 대한 flops 계산 코드가 있음 (111번 라인)
https://github.com/ultralytics/yolov5/blob/master/utils/torch_utils.py#:~:text=def%20profile(input%2C%20ops%2C%20n%3D10%2C%20device%3DNone)%3A
    - yolo v5 github issue에 tf로 convert한 yolov5 모델도 torch_utils 코드로 계산이 가능한지 질문을 남겨 답변을 받았고, 실제로 측정이 되는지 확인 필요
    https://github.com/ultralytics/yolov5/issues/8844
    - github 코드에서 사용한 flops 계산 방식이 thop의 profile을 사용
        - keras-flops 라이브러리 처럼 torch 모델 flops 계산 라이브러인듯
        - torch 모델을 다루는 라이브러리 이므로 TF 모델에 대한 flops 계산이 이루어지지 않을 것이라 예상하고, 답변을 받는 동안 다른 방법도 확인
    - model_profiler 라이브러리 사용 (yolo v5 - tensorflow model)
    https://pypi.org/project/model-profiler/
       - 아래와 같은 에러가 발생하여 확인중에 있음
       ```
       AttributeError: '_UserObject' object has no attribute 'layers'
       ```
       - model의 TF 버전 차이로 인한 문제로 판단되어 파악하고 있음
       - original yolo v5 model이 pytorch 기반으로 작성되었고, 이를 TF v2 버전으로 convert해서 사용하다보니, 이슈가 생기는 것으로 판단됨

**Comment by jungae-park** [comment]
**edgetpu tflite model flops 계산 추가 확인 (2가지 방법)**

1. tflite-flops 
https://github.com/lisosia/tflite-flops (batch 단위별 측정 불가능)

위의 댓글에서 mobilenet v1, mobilenet v2, inception v3 모델은 tflite-flops로 측정을 할 때, 
에러는 발생하지 않았지만 아래와 같이 0으로 측정되었습니다.
```
# tf2_mobilenet_v1_1.0_224_ptq_edgetpu.tflite 
OP_NAME            | M FLOPS
------------------------------
CUSTOM             | <IGNORED>
------------------------------
Total: 0.0 M FLOPS
# tf2_mobilenet_v2_1.0_224_ptq_edgetpu.tflite 
OP_NAME            | M FLOPS
------------------------------
CUSTOM             | <IGNORED>
------------------------------
Total: 0.0 M FLOPS
# inceptionv3_edgetpu.tflite 
OP_NAME            | M FLOPS
------------------------------
CUSTOM             | <IGNORED>
------------------------------
Total: 0.0 M FLOPS
```
tflite-flops로 계산하였을 때, https://github.com/lisosia/tflite-flops/blob/main/tflite_flops/calc.py 코드상에서  Conv, DepthwiseConv layer만 고려하여 계산을 진행하기 때문에 값이 계산되지 않고 0으로 출력되는 것으로 예상됩니다.
하지만 yolo v5 edgetpu tflite (int8) 모델은 위의 댓글 처럼 측정이 되었고, 
yolo v5 tflite (FP16, INT8) 모델도 아래와 같이 측정됩니다.

** yolo v5 - FP16
Total: 16433.6 M FLOPS
** yolo v5 - INT8
Total: 16433.6 M FLOPS

2. flopco-keras
해당 방법은 keras API 모델만 지원, tflite 모델은 지원하지 않았습니다.

시중에 나와있는 tflite model flops 측정 방법은 모두 활용을 해보았지만, 제대로 측정이 되는 것이 없었고 측정이 되더라도 모델의 모든 layer를 커버하여 측정되고 있지 않습니다.

그리고 tflite 모델 flops 계산 불가능 관련 글을 아래와 같이 찾았습니다.
https://copyprogramming.com/howto/measuring-flops-for-tflite-model-in-tensorflow-2-x#:~:text=Unfortunately%2C there's no direct way you can calculate the FLOPS for a tflite model
```
Unfortunately, there's no direct way you can calculate the FLOPS 
for a tflite model.
```
다른 논문들에서도 tflite 모델의 flops를 측정한 것을 찾을 수가 없었습니다.

**Comment by jungae-park** [comment]
**Tensorflow FP32 yolo v5 model flops 계산 추가 확인 (2가지 방법)**

1. yolo v5 github의 torch_utils 코드에 torch 모델에 대한 flops 계산 코드

위의 댓글에서 참고한 yolo v5 github에 flops 계산 코드를 발견하여 tensorflow로 convert를 진행한 yolo v5 모델도 해당 코드로 flops를 계산 할 수 있는지 질문을 남겼고, 
"exported models are identical, FLOPs are identical" 라고 답변을 달아주셨습니다.

이것을 original yolo v5 (pytorch) 모델의 flops 값을 활용해도 된다는 말로 해석해도 될런지 궁금합니다.
original yolo v5 (pytorch) 모델의 flops는 아래와 같이 측정되었습니다. 
(저희 모델은 yolov5s 모델입니다.)
https://pytorch.org/hub/ultralytics_yolov5/
<img width="778" alt="image" src="https://user-images.githubusercontent.com/46885199/183004110-9fcc2573-ad74-48a8-b26f-a7f5eac349dc.png">

2. model_profiler

위의 댓글에서 전달 드린 것처럼 original yolo v5 model이 pytorch 기반으로 작성되었고, 이를 TF v2 버전으로 convert해서 사용하다보니, 이슈가 생기는 것으로 판단되며 아직 해결이 되고 있지 않습니다.

**Comment by hyu-leeky** [comment]
응 정애야. 업데이트를 많이 놓치고 있었구나. 여러가지 경우를 잘 시도를 해봤네. 되는것도 있고 안되는 것도 있지만 그래도 이제 많이 커버가 된것 같기도 하네. 혹시 현재 진행 상황을 (되는 것과 안되는 모델 및 플랫폼) 표 같은 걸로 만들어서 간단히 공유해줄래? 일부 변환 모델에서 성공한 경우는 그냥 그 값을 사용해도 괜찮을것 같아서. 

그리고 이 이슈는 전체 적인 연구 내용 보다는 결국 세부 구현에 가깝겠다는 생각이 들어서, research-issues 가 아닌 다른 개발 리포로 옮기는건 어떨까?

**Comment by jungae18** [comment]
현재 flops 계산이 되는 것과 안되는 모델 및 플랫폼에 대해 표로 간단히 작성해보았습니다.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/46885199/183353715-59cf44e7-d542-421e-948a-5c2c358bb8de.png">

이슈는 새로운 repository를 만들어 세부 구현 코드와 같이 관리하기 위해 이동하였습니다.
https://github.com/ddps-lab/edge-management-module

**Comment by jungae18** [comment]
현재 flops 계산이 되는 것과 안되는 모델 및 플랫폼에 대해 표로 간단히 작성해보았습니다.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/46885199/183353715-59cf44e7-d542-421e-948a-5c2c358bb8de.png">

이슈는 새로운 repository를 만들어 세부 구현 코드와 같이 관리하기 위해 이동하였습니다.
https://github.com/ddps-lab/edge-management-module

**Comment by jungae18** [comment]
test

**Comment by jungae18** [comment]
test

**Comment by jungae-park** [comment]
현재 flops 계산이 되는 것과 안되는 모델 및 플랫폼에 대해 표로 간단히 작성해보았습니다.

![image](https://user-images.githubusercontent.com/46885199/183357324-79242d16-8084-4beb-9392-26196fd5484e.png)


새로운 repository를 만들어 flops 계산이 가능한 모델에 대한 측정 코드를 업데이트하여 같이 관리하겠습니다.
https://github.com/ddps-lab/edge-management-module

**Comment by hyu-leeky** [comment]
오케이. 표로 보니 확실히 보기가 좋다. 다른 리포에서 계속 추적해보자.

**Comment by jungae-park** [comment]
FLOPS 계산이 가능한 모델과 값을 참고할 자료를 포함하여 코드와 계산 값을 표로 정리하여 PR 진행하였으며, 
계산이 불가능한 모델은 위의 댓글에서 말씀드린 EdgeTPU-tflite-INT8로 양자화된 MobileNet V1, V2, Inception V3 모델입니다.

이 모델은 위의 댓글에서 말씀드린 것처럼 tflite 모델 flops 계산 불가능 관련 글을 아래와 같이 찾았었습니다.
https://copyprogramming.com/howto/measuring-flops-for-tflite-model-in-tensorflow-2-x#:~:text=Unfortunately%2C 
{there's no direct way you can calculate the FLOPS for a tflite model}

다른 논문들에서도 tflite 모델의 flops를 측정한 것을 찾을 수가 없었고,
yolo v5 모델에서도 convert를 하여도 사용한 layer가 같기 때문에 flops가 비슷한 것으로 예상되어, 따로 계산을 하거나 찾지 않고 TF-FP32 모델의 flops 값을 활용해도 괜찮을 것 같다는 생각이 듭니다.

**Comment by hyu-leeky** [comment]
오케이. 이정도면 많이 알아본듯 하다. 다음주에 만나서 계산된 FLOPS 보면서 같이 이야기를 나눠보자.
