### ISSUE TITLE
FLOP/Parameters 계산값 분석

### ISSUE THREAD

**Issue by jungae-park** [ddps-lab/edge-management-module#11]
![image](https://user-images.githubusercontent.com/46885199/185336257-19eeca35-741b-42a5-8ef7-72964f389abc.png)

업데이트된 summary table을 보고, flops/parameter 값을 metric에 채우고 있으며 값 분석을 진행하려고 합니다.
https://docs.google.com/spreadsheets/d/1hhYyZWexZVVmE8NIR5lIlMwPGjTQkHUEFYAR46YJ9tw/edit#gid=1792697168

1. xavier 장비의 batch 1기준으로 성능 측정한 메트릭과 비교하였을 때, flops 만큼의 성능을 보이지 않은 경우 발생
2. flops/parameter 표를 채움
    1. 양자화를 진행하여도 파라미터 값이 같은지 확인 필요
    2. 다르다면, yolo v5 (edgetpu, tflite) 모델의 파라미터 값 계산 필요
3. flops/parameter 값과 성능과의 상관 관계를 주목할 필요성 확인

**Comment by hyu-leeky** [comment]
오케이. 좋다. 잘 진행해보자. #3 과 연계해서 스케줄러를 만드는 방안도 괜찮을것 같기도 하고. 우선 조금 더 분석을 해보자.

**Comment by jungae-park** [comment]
채우지 못한 yolo v5 (edgetpu, tflite) 모델의 파라미터 값에 대해 확인해보고, flops/parameter 표를 채워보았으며 스케줄러로 활용할만한 지표가 무엇이 있을지 분석해보고 있습니다.

1. flops/parameter table 
    1. 양자화를 진행하여도 파라미터 값이 같은지 확인
        1. 양자화는 실수형 변수를 정수형 변수로 변환하는 과정이므로 FP32 모델을 INT8로 convert 하여도 파라미터값은 FP32 모델의 것을 그대로 사용하는 것으로 추정됨
        ![image](https://user-images.githubusercontent.com/46885199/185866002-9cf6cd62-e624-4f76-ad6c-dbb361b67c2e.png)
        2. 양자화를 통해 용량을 줄여 모델 size를 축소할 수 있고, bit 수를 줄이므로써 계산 복잡도를 줄여 모델의 연산량을 감소 시킬 수 있음
    2. tflite로 convert 하게되면, 모델의 parameter 정보를 추출 할 수 있는 API가 없으며 양자화를 진행하여도 파라미터 사이즈는 변하지 않으므로 그대로 사용해도 괜찮을 듯함
    3. model size를 parameter size 대신 대체 사용 가능한지 확인
        1. 양자화된 모델 사이즈는 float 타입을 int형으로 줄여 용량을 줄인 것이고, 
        파라미터 사이즈는 FP32 원본 모델의 파라미터 사이즈를 가져온 것이라 둘을 같은 것으로 볼 수 없어 대체 사용이 불가능해보임
2. 채운 flops/parameter 값과 성능과의 상관 관계를 주목할 필요성 확인
https://docs.google.com/spreadsheets/d/1dN5pcS9TgCm0JoGnjTLiqUnjDQ03oVMhpqWo0mMFF34/edit#gid=86153796
![image](https://user-images.githubusercontent.com/46885199/185866847-866838ee-e1c5-49e0-aca3-2851053cac0d.png)
    1. flops는 모델이 추론시 필요로하는 연산량, parameter는 모델의 크기
    2. 표의 flops/parameter 값이 높을 수록 모델의 크기가 가볍고 추론 속도가 빠르다고 볼 수 있음
        1. Nvidia Jetson device, TF-FP32 모델 
            1. Yolo V5 - Inception V3 - Mobilenet V1 - Mobilenet V2 순으로 성능이 좋아보임
        2. Nvidia Jetson device, tflite-FP16/INT8 모델
            1. Yolo V5 (TF-FP32) 모델 만큼의 성능을 나타냄
        3. EdgeTPU device, edgetpu-tflite-INT8 모델
            1. Yolo V5 (TF-FP32) 모델보다 성능이 좋아 보이지 않음
    3. 실제 추론시 측정한 메트릭 값과 비교https://docs.google.com/spreadsheets/d/1hhYyZWexZVVmE8NIR5lIlMwPGjTQkHUEFYAR46YJ9tw/edit#gid=1792697168
        1. 계산한 flops/parameter와 측정한 IPS 성능을 비교했을 때, 장비마다 flops spec이 다르기 때문에 flops 만큼의 성능을 보이지 않은 경우가 있음
        2. 스케줄러에 활용할 지표들이 무엇이 있을지 계속 분석 예정

**Comment by hyu-leeky** [comment]
오케이 정애야 잘하고 있다. 
위에서 이야기한 model size 는 파일로 저장된 모델의 파일 크기를 이야기 하는거야?
flops 는 연산 능력, parameter 수 는 메모리 사이즈 및 성능과 연관시켜서 보면 좋을것 같아.

현재 타겟팅하는 모델이 조금 작은 감이 있어서 nlp 도 추가해서 같이 분석해보면 좋을것 같아.

**Comment by jungae-park** [comment]
네 위에서 말씀드린 model size는 파일로 저장된 모델의 크기를 말합니다.
flops와 parameter를 메모리 사이즈와 성능과 연관시켜 살펴보겠습니다.
그리고 nlp 모델도 flops/parameter가 계산 될 수 있는지 확인해보겠습니다.

**Comment by jungae-park** [comment]
기존에 존재하고 있는 flops 계산 라이브러리의 코드를 활용하여 DNN 모델의 flops 값을 계산 할 수 있도록 합니다.

[작업 방향]

* CNN, NLP 모델 구조 파악
기존에 수빈이가 모델의 op 구조 파악에 관해 이슈 내용을 정리한 것을 jira를 통해 확인해보았습니다.
https://kmu-bigdata.atlassian.net/browse/DEEPCLD-228
torch 모델 기반으로 구조를 파악한 것이여서, tensorflow 모델 기반으로 구조 파악을 하기 위해 참고하고 있습니다.
* 각 모델의 op 마다 flops 계산 방법 확인 (keras_flops 라이브러리 코드 참고)
* 여러 모델이 입력으로 들어와도 flops 값이 계산 될 수 있도록 코드 작성

**Comment by jungae-park** [comment]
**[현재 작업 상황]**

- keras api로 제공하는 cnn 모델의 경우 operation을 summary로 확인 가능
- edgetpu-tflite로 convert된 모델의 operation을 summary로 확인이 어렵지만 keras api로 제공하는 모델과 op는 같을 것으로 예상
- keras-flops : [https://pypi.org/project/keras-flops/]
라이브러리의 공식 python 홈페이지에서 확인하면 support 하는 op 종류 확인 가능
![image](https://user-images.githubusercontent.com/46885199/188532263-cc4cd8a9-5d44-4f69-b83a-75a9f8b8b7c0.png)

- keras-flops 라이브러리가 각 op 마다 어떻게 flops를 계산하는지에 대한 코드 확인[https://github.com/tokusumi/keras-flops/blob/5c130bfe91d39eea39af89346b029e70c3351999/keras_flops/flops_calculation.py#L4]
- 각 layer 마다 자세한 코드가 공개되어 있지 않아 추가로 살펴봐야함
- 따라서 cnn 모델의 경우 기존에 flops 계산이 불가능 했던 모델의 대해 계산이 가능할지 확인중에 있음
(mobilenet v1-edgetpu-tflite, mobilnet v2-edgetpu-tflite, inception v3-edgetpu-tflite)
- nlp 모델의 경우 keras-flops 라이브러리에서 support 해주지 않는 op에 속해 있어 keras-flops 라이브러리에서 사용한 계산 코드가 아닌, 다른 방법으로 계산 방법을 찾아야 할 필요가 있어보임
![image](https://user-images.githubusercontent.com/46885199/188532293-267b01dc-6b3e-41fc-9f03-f25b0c31aa0a.png)

**Comment by jungae-park** [comment]
* CNN model flop, parameter 
paper : Characterizing the Deployment of Deep Neural Networks on Commercial Edge Devices
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9041955

* NLP model flop, parameter
paper : Towards Efficient NLP: A Standard Evaluation and A Strong Baseline
https://arxiv.org/pdf/2110.07038.pdf

각 논문의 저자들에게 cnn, nlp 모델의 flop, parapeter 계산 값을 그대로 사용해도 되는지와 계산 할 수 있는 참고할 자료에 대해 메일을 보내놓았습니다.
회신이 오면 업데이트 하겠습니다.

**Comment by hyu-leeky** [comment]
good!

**Comment by jungae-park** [comment]
NLP model flop, parameter
paper : Towards Efficient NLP: A Standard Evaluation and A Strong Baseline
https://arxiv.org/pdf/2110.07038.pdf

논문의 저자에게서 아래와 같이 메일 답장이 왔습니다.
```
Hello

You can directly refer to the FLOPs and Parameter values in our paper, but please cite our paper. Thank you for following our work!
```
<img width="625" alt="image" src="https://user-images.githubusercontent.com/46885199/189229903-9c18a5e2-54ea-4ea8-a38d-a53682e705d4.png">

위 논문의 table 2에 해당하는 BERT, DistilBERT 모델의 parameter, flops 값을 활용해도 좋을 것 같습니다.
저희가 사용한 BERT가 논문에서 말하는 base or large 모델인지 추가로 확인하여 값을 쓸 수 있는지 보겠습니다.

**Comment by hyu-leeky** [comment]
음 어떻게 계산했는지에 이야기는 없네..
답장을 보내서 고맙다고 하고, 바로 사용을 하겠다. 그런데 계산해낸 방법이나 출처를 알 수 있겠냐고 한번 더 물어볼래?
사용은 하더라도 계산 방법 정도는 잘 알고 사용하는게 좋을것 같아. 모델이 똑같다고 가정할수도 없는것이니.

**Comment by hyu-leeky** [comment]
메일 보내기 전에 내용을 공유해주면 같이 검토해보고 발신하면 좋을것 같아.

**Comment by jungae-park** [comment]
아래와 같이 답장을 보내려고합니다.
```
Thank you for your mail reply.

We will refer to the paper for that value and use it.
By the way, could you provide additional information on how you calculated the value or the source?
```

Towards Efficient NLP: A Standard Evaluation and A Strong Baseline의 table2에 해당하는 nlp 모델중
BERT(BASE)와 DistilBERT 모델 (IMDb dataset) 두가지의 flops, parameter 값을 사용 할 수 있을 것 같습니다.
이전에 운호가 계산한 두 모델의 parameter 값과 유사해보입니다.

추가로 메일을 보내고 계산 방법이나 출처를 알게되면 저도 값을 확인 및 계산해보려고합니다.

**Comment by hyu-leeky** [comment]
응 정애야 잘 작성했네. 이렇게 진행해보자.

**Comment by jungae-park** [comment]
저자로부터 
 https://github.com/fastnlp/ElasticBERT/tree/main/FLOPs 를 참고하여 모델의 flops를 계산했다고 답장을 받았습니다.

해당 코드를 살펴보고 저희 모델도 계산을 진행해보겠습니다.

**Comment by hyu-leeky** [comment]
나이스! 잘알아냈다.

**Comment by jungae-park** [comment]
해당 이슈도 close하고 추후 업데이트 사항이 있을 경우 이슈를 새롭게 생성하겠습니다.
