### ISSUE TITLE
k3s 에서 나노 혹은 xavier 활용한 추론 가능 여부 확인

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/edge-management-module#12]
시도해볼만한 소스가 여럿있는듯 하니 한번 시도해보고 결과를 공유해주면 좋을듯.

**Comment by hyu-leeky** [comment]
운호야 진행된 내용 있으면 공유해줘.

**Comment by jungae-park** [comment]
우선 희가 xavier 장비에서 k3s를 설치하고 gpu를 하나를 모두 사용하여 pod-container를 띄울수 있을지 확인합니다.

**Comment by hyu-leeky** [comment]
오케이. 그러자.

**Comment by HeeNamgoong** [comment]
현재 https://wiki.seeedstudio.com/Jetson-Mate/#getting-started 를 참고해 xavier2 장비의 k3s설치, master 서버와 workernode 클러스터 구성하기를 진행중에 있습니다.

**Comment by HeeNamgoong** [comment]
해당이슈는 k8s 실험결과로 대체되어 close하겠습니다.
