### ISSUE TITLE
엣지 장비에서 k8s 클러스터 구성후 다양한 시나리오로 GPU 공유 여부 확인

### ISSUE THREAD

**Issue by jungae-park** [ddps-lab/edge-management-module#17]
#3 이슈와 연관이 있으며 아래와 같은 단계로 실험을 진행해보려고 합니다.

1. master(ubuntu desktop) - edge device worker node (xavier, tx2, nano) 클러스터 구성
2. 엣지 장비 노드에서 별다른 리소스 요청 할당 없이 yaml 파일을 구성하여 pod-container를 띄우고 추론 코드 실행시 gpu에 접근하여 사용가능한지 확인
3. 엣지 노드 장비에서 gpu를 할당하는 옵션을 yaml 파일에 구성하는 것이 불가능하여, cpu 리소스 할당을 달리하여 활용 측면에서 성능 비교
4. cpu intensive한 워크로드를 돌릴떄와 추론 코드를 돌릴 때 cpu, gpu 사용률 확인
5. 할당된 cpu core 수가 같을 때, gpu에 접근하는 pod이 많을 때 성능 비교

**Comment by jungae-park** [comment]
1. master(ubuntu desktop) - edge device worker node (tx2, xavier, nano) 클러스터 구성
[daemonset yaml file](https://encouraging-lantern-5d1.notion.site/deamonset-4302e31a53b345d38b5fbf1d9cb23090)
```jsx
root@master:~/jungae# kubectl get node
NAME             STATUS   ROLES    AGE     VERSION
master           Ready    master   34d     v1.18.14
nvidia-nano1     Ready    worker   34h     v1.18.14
nvidia-tx2       Ready    worker   7m27s   v1.18.14
nvidia-xavier1   Ready    worker   13d     v1.18.14
```

```jsx
root@master:~/jungae# kubectl get pod -o wide
NAME                      READY   STATUS    RESTARTS   AGE   IP            NODE             NOMINATED NODE   READINESS GATES
gpu-cpu-daemonset-2728p   1/1     Running   0          36s   10.244.6.15   nvidia-xavier1   <none>           <none>
gpu-cpu-daemonset-cjdb9   1/1     Running   0          36s   10.244.1.6    nvidia-nano1     <none>           <none>
gpu-cpu-daemonset-r9vr6   1/1     Running   0          36s   10.244.2.4    nvidia-tx2       <none>           <none>
```

2. 엣지 장비 노드에서 별다른 리소스 요청 할당 없이 yaml 파일을 구성하여 pod-container를 띄우고 추론 코드 실행시 gpu에 접근하여 사용가능한지 확인

- tx2
    - gpu 접근 및 사용 가능
    - cpu 최대 1123m, gpu 최대 78% 사용

- xavier
    - gpu 접근 및 사용 가능
    - cpu 최대 1134m, gpu 최대 32% 사용

- nano의 경우 pod-container 생성 후 gpu 접근까지는 가능하지만 추론시 메모리 부족으로 killed 되어 확인해보니, 
메모리 사용률이 기본적으로 높고 cached 되어 있는 메모리가 많아 정리를 해보고 다시 추론시 gpu를 사용하는지 다시 확인해보려고 합니다.
```bash
root@nvidia-nano1:~# free -m
              total        used        free      shared  buff/cache   available
Mem:           3964        2506         560          96         897        1487
Swap:             0           0           0
root@nvidia-nano1:~# 
root@nvidia-nano1:~# 
root@nvidia-nano1:~# cat /proc/meminfo 
MemTotal:        4059240 kB
MemFree:          573912 kB
MemAvailable:    1523828 kB
Buffers:           21056 kB
Cached:           833768 kB
SwapCached:            0 kB
Active:          1407124 kB
Inactive:         471264 kB
Active(anon):    1040544 kB
Inactive(anon):    97168 kB
Active(file):     366580 kB
Inactive(file):   374096 kB
Unevictable:       15400 kB
Mlocked:              16 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:       1037108 kB
Mapped:           211712 kB
Shmem:             98764 kB
Slab:             152508 kB
SReclaimable:      63932 kB
SUnreclaim:        88576 kB
KernelStack:       12992 kB
PageTables:        17596 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2029620 kB
Committed_AS:    7215296 kB
VmallocTotal:   263061440 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
AnonHugePages:    389120 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
NvMapMemFree:     309000 kB
NvMapMemUsed:     970444 kB
CmaTotal:         475136 kB
CmaFree:          246552 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
```

**Comment by jungae-park** [comment]
nano 장비에서 k8s cluster worker node로 구성후, 아무조건 없이 gpu 접근 및 사용이 가능한지 확인하기 위해 container를 생성하고 추론을 하였으나, killed 메시지 반환 후 메모리 부족으로 추론이 완료되지 않았습니다.

다른 논문이나 참고 글을 확인하였을 때, nano 환경에서 k8s cluster 구성을 많이 해 본 사례가 있었습니다.
(저의 실험에서도 cluster 구성까지는 잘 되어 있기는 합니다.)
그래서 nano 장비 재설치 후 깨끗한 환경 부터의 메모리 확인 ~ 아래와 같은 단계로 docker container에서 추론시 사용되는 메모리와 비교하여 진행하였을 때 메모리 사용이 어느 정도인지 각각 확인을 해보았습니다.

- nano memory debugging
    - os 기본 설치후 메모리 확인
        
        ```bash
        total        used        free      shared  buff/cache   available
        Mem:           3956        1945        1263          24         747        1955
        Swap:          1978           0        1978
        ```
        
    - docker image pull 후 메모리 확인
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2128         487          23        1339        1606
        Swap:          1978          55        1922
        ```
        
    - buff/cache 정리 후 메모리 확인
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2096        1666          22         193        1672
        Swap:          1978          55        1922
        ```
        
    - os 기본 설치시 docker도 자동으로 설치되어 docker에서 container 생성시 메모리 확인
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2139        1111          22         705        1624
        Swap:          1978          54        1923
        ```
        
    - dataset download 후 메모리 확인
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2141        1001          22         813        1621
        Swap:          1978          54        1923
        ```
        
    - docker container 생성 후 keras api로 model download 및 추론후 메모리 확인 및 성능 측정
        
        [[전체 결과 메시지 (docker container inference)](https://www.notion.so/docker-container-inference-ede6cf2c09d645fd84118a63d1c62d40)](https://www.notion.so/docker-container-inference-ede6cf2c09d645fd84118a63d1c62d40)
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        3520         298           0         137         285
        Swap:          1978        1105         872
        ```
        
        ```bash
        ***** TF-FP32 matric *****
        user_batch_size = 1
        accuracy = 0.93
        model_load_time = 70.6007673740387
        dataset_load_time = 2.3073651790618896
        inference_time = 155.28422498703003
        inference_time(avg) = 0.15093003916740416
        IPS = 4.38226227005257
        IPS(inf) = 6.625586301550277
        ```
        
        - gpu 접근 및 사용 가능
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2040        1460           0         455        2180
        Swap:          1978         829        1148
        ```
        
        - 추론 후 사용하던 메모리가 자동으로 반환되어 돌아왔고, 추론시 800MB 정도를 사용하고 있었음
    - k8s install 후 메모리 확인
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2637         244          24        1073        1539
        Swap:             0           0           0
        ```
        
    - 설치 후 메모리가 자동으로 반환되지 않아 buff/cache 정리 후 메모리 확인
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2234        1505          24         216        1530
        Swap:             0           0           0
        ```
        
    - k8s cluster worker node 구성후 메모리 확인
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2361         692          25         902        1387
        Swap:             0           0           0
        ```
        
    - k8s cluster woker node로 구성되기 위해 추가 구성을 위해 nano에 자동으로 생성되는 컨테이너들
        
        ```bash
        root@nvidia-nano1:~# docker ps
        CONTAINER ID   IMAGE                              COMMAND                  CREATED              STATUS              PORTS     NAMES
        1613024e94dd   nvcr.io/nvidia/k8s-device-plugin   "nvidia-device-plugi…"   About a minute ago   Up About a minute             k8s_nvidia-device-plugin-ctr_nvidia-device-plugin-daemonset-wm4xn_kube-system_43a15bfa-9f0e-4f12-8e06-8ccd49f350fe_0
        e9d3795794d4   k8s.gcr.io/pause:3.2               "/pause"                 About a minute ago   Up About a minute             k8s_POD_nvidia-device-plugin-daemonset-wm4xn_kube-system_43a15bfa-9f0e-4f12-8e06-8ccd49f350fe_1
        06973488f2e7   0729779a30a1                       "/opt/bin/flanneld -…"   2 minutes ago        Up 2 minutes                  k8s_kube-flannel_kube-flannel-ds-6sd9l_kube-system_09b24c7d-9169-433c-b621-4801319a146e_0
        6b4659bb60a2   k8s.gcr.io/kube-proxy              "/usr/local/bin/kube…"   2 minutes ago        Up 2 minutes                  k8s_kube-proxy_kube-proxy-mwrbb_kube-system_612f21fd-8d54-4614-9773-90d895b7b158_0
        64b7c8c9f4b1   k8s.gcr.io/pause:3.2               "/pause"                 2 minutes ago        Up 2 minutes                  k8s_POD_kube-proxy-mwrbb_kube-system_612f21fd-8d54-4614-9773-90d895b7b158_0
        5d9519183051   k8s.gcr.io/pause:3.2               "/pause"                 2 minutes ago        Up 2 minutes                  k8s_POD_kube-flannel-ds-6sd9l_kube-system_09b24c7d-9169-433c-b621-4801319a146e_0
        ```
        
        - docker container 생성에는 따로 자동으로 생성되는 컨테이너는 없음
    - 메모리가 자동으로 반환되지 않아 buff/cache 정리 후 메모리 확인
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2346        1200          25         409        1412
        Swap:             0           0           0
        ```
        
    - k8s cluster 구성에서 nano node에 아무 조건없이 container 생성후 메모리 확인
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2362         773          26         820        1392
        Swap:             0           0           0
        ```
        
    - 메모리가 자동으로 반환되지 않아 buff/cache 정리 후 메모리 확인
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2362        1182          26         411        1395
        Swap:             0           0           0
        ```
        
    - k8s cluster 구성에서 nano node에 생성한 컨테이너에서 dataset, model download 및 추론 후 메모리 확인
        
        [[전체 결과 메시지 (k8s cluster container inference)](https://www.notion.so/k8s-cluster-container-inference-faa78d9c1fcf4c64bd962df9dde75994)](https://www.notion.so/k8s-cluster-container-inference-faa78d9c1fcf4c64bd962df9dde75994)
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        3661          69          25         225          96
        Swap:             0           0           0
        ```
        
        ```bash
        killed
        ```
        
        ```bash
        root@nvidia-nano1:~# free -m
                      total        used        free      shared  buff/cache   available
        Mem:           3956        2624         891          25         440        1436
        Swap:             0           0           0
        ```
        
        - 1.1GB이상 사용하다가 killed 되었고, docker container에서 추론하는 것보다 메모리가 더 많이 필요하고 추론후 메모리가 자동으로 800MB 밖에 반환되지 않음
        - k8s cluster에 필요한 구성요소들이 메모리를 그렇게 사용하고 있는 것도 아니고 추론에만 메모리를 사용하고 있음
            
            ```bash
            top - 17:25:46 up 50 min,  3 users,  load average: 30.80, 16.68, 7.42
            Tasks: 342 total,   2 running, 340 sleeping,   0 stopped,   0 zombie
            %Cpu0  :  0.1 us,  9.2 sy,  0.0 ni,  2.1 id, 86.4 wa,  1.2 hi,  0.9 si,  0.0 st
            %Cpu1  :  0.0 us, 22.5 sy,  0.0 ni,  0.0 id, 76.9 wa,  0.3 hi,  0.4 si,  0.0 st
            %Cpu2  :  0.1 us, 15.4 sy,  0.0 ni,  5.3 id, 78.7 wa,  0.4 hi,  0.1 si,  0.0 st
            %Cpu3  :  0.1 us, 13.5 sy,  0.0 ni,  9.2 id, 76.6 wa,  0.3 hi,  0.3 si,  0.0 st
            KiB Mem :  4051048 total,   224180 free,  3660120 used,   166748 buff/cache
            KiB Swap:        0 total,        0 free,        0 used.   211148 avail Mem 
            
              PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                         
              879 root      20   0       0      0      0 R  37.9  0.0   2:02.23 kswapd0                                         
             1895 root      -2   0       0      0      0 S  13.8  0.0   1:21.91 mmcqd/0                                         
            14511 root      20   0 1611368  37256      0 S   2.7  0.9   1:42.66 kubelet                                         
             4607 root     -51   0       0      0      0 S   2.1  0.0   0:33.50 sugov:0                                         
            19171 root      20   0  139008   9104      0 S   1.5  0.2   0:36.96 kube-proxy                                      
            19497 root      20   0  738512  11000      0 S   1.5  0.3   0:08.67 flanneld                                        
             4673 root      20   0 1333112  30960      0 S   1.2  0.8   0:12.14 containerd                                      
            24934 root      20   0   10564   1836    884 R   1.2  0.0   0:00.80 top                                             
            23691 root      20   0 11.216g 0.978g 103368 D   0.8 25.3   1:40.56 python3
            ```
            
        - 자동으로 메모리 반환이 잘 이루어지지 않은 것 같고, 수동으로 해줘야 그나마 dataset, model load 까지만 사용하고 추론시에는 메모리가 부족함

**Comment by jungae-park** [comment]
위의 과정에서 메모리 사용이 어떻게 이루어지고 있는지 확인하였을때, 
docker container 생성 후 추론 작업시 사용되는 메모리와 k8s cluster 구성후 nano node에서 pod-container를 생성 후 추론 작업시 사용되는 메모리가 달랐습니다.
k8s cluster 구성으로 인해 메모리를 더 사용하는 것인줄 알았지만 그렇지 않아, 이유를 찾아보던 중 k8s 환경에서 메모리 제한에 따른 비슷한 이슈를 발견하였습니다.
https://stackoverflow.com/questions/71519202/kubernetes-memory-leak-troubleshooting
현재 저희 실험에서 사용하고 있는 k8s 버전은 1.18.4 버전입니다.
이슈에서는 1.21.11 버전으로 업그레이드하여 문제를 해결하였고, 제가 이해하기로는  kubernetes 공식 github에 따르면 객체를 생성하고, 읽고 쓴 후 메모리 반환하는 부분에 오류가 있어 보입니다.

그래서 버전을 업그레이드를 해봐야할지 궁금합니다.
현재 kubernetes 최신 버전은 1.25까지 릴리즈 되었습니다.

**Comment by hyu-leeky** [comment]
이제야 메시지를 봤네. 깃허브 빨리 수정이 되기는 해야겠다.
정애가 제시해준 데이터를 보면 k8s 가 메모리가 더 필요해보이기는 하네. 메모리가 반환되지않는 누수가 원인이라면 패치를 통해서 결과가 나아지기를 기대할수는 있을듯 하네. 그런데 이것때문에 전체를 새로 설치하는건 부담이 조금 클것 같고, 나노는 이정도 이슈로 정리를 해두고. TX2 에서는 결과 확인이 다 되었나?
그리고 나노의 경우 다커 로 추론 할 경우에 스왑 스페이스를 사용하는것 같아서 성능에 안좋은 영향일 클것 같은 생각이 들기도 한다. @kmu-leeky

**Comment by jungae-park** [comment]
@kmu-leeky 
네 tx2, xavier 장비는 k8s cluster로 구성하고 아무 옵션을 주지 않았을때, gpu 접근 및 사용이 가능한 것 까지 확인하였습니다.
그럼 두 장비 먼저 다른 시나리오 실험을 진행해보고 있을까요?

**Comment by hyu-leeky** [comment]
응 정애야 그러자. 나노에서 k8s 는 조금 후순위로 둬도 될듯하다. tx2, xavier 에서 다양한 시나리오에서 실험을 진행해보자.

**Comment by jungae-park** [comment]
@kmu-leeky 
네 알겠습니다. 시나리오 구성 후 정리해서 다시 업데이트하겠습니다.

**Comment by jungae-park** [comment]
모든 cpu core를 사용하여 하나의 컨테이너를 띄우고, 여러 추론 코드 멀티 실행시 cpu, gpu 사용률 확인

시나리오 전체 결과 값은 아래 링크에서 자세하게 확인 할 수 있습니다.
https://encouraging-lantern-5d1.notion.site/3-69855365b8634a02b49e3dd5410c3d31 

결론 1.
xavier 장비의 경우 cpu core를 7개까지 사용할 수 있었으며, 
최대 7개까지 추론 코드를 멀티 실행 할 수 있었습니다. 
(하나의 추론 코드 실행시 cpu 1000m 이상 쓰는 것을 이전 실험에서 확인한 적이 있었음)
그리고, 7개의 추론 코드를 멀티 실행시 cpu 최대 7084m, gpu 최대 96%로 사용하고 있었고 성능은 docker container에서 추론 했을 때의 성능과 비교하였을때 떨어졌습니다.

결론 2. 
tx2 장비의 경우 공홈에서 tx2 cpu core spec이 4개로 나와있지만
cpu 6개 까지 모두 사용하도록 on은 할 수 있는데, 실제 사용은 4개만 사용가능하였습니다.
그래서 최대 3개까지 추론 코드를 멀티로 실행할 수 있을 것이라고 생각하였지만
memory 부족으로 최대 2개까지 코드를 실행할 수 있었습니다.
그리고, 2개의 추론 코드를 멀티 실행시 cpu 최대 3787m, gpu 최대 32% 사용하고 있었고 성능은 docker container에서 추론 했을 때의 성능과 비교하였을때 떨어졌습니다.


이후 시나리오 실험은 아래와 같이 진행하려고 합니다.

- 모든 cpu core를 사용하며 가능한 여러개의 컨테이너를 띄우고, 동시 추론 시 cpu, gpu 사용률 확인
- 모든 cpu core를 사용하는 하나의 컨테이너를 띄우고,
cpu intensize한 워크로드와 추론 코드를 각각 돌렸을 때 cpu, gpu 사용량 확인
- xavier 장비의 경우 cpu request (1,2,4,7) or tx2 장비의 경우 cpu request (1,2,3) 에 따라 점차 늘려 하나의 컨테이너를 띄웠을때,
하나의 추론 코드 실행 시 늘어난 cpu request 만큼 cpu 사용량도 증가하는지 확인하고 gpu 사용률 확인
- xavier 장비의 경우 cpu request (1,2,4,7) or tx2 장비의 경우 cpu request (1,2,3) 에 따라 점차 늘려 하나의 컨테이너를 띄웠을때,
여러개의 추론 코드를 동시 실행하여 같은 gpu에 접근 하는 프로스세스가 많을 때 cpu, gpu 사용률 확인
- xaiver 장비의 경우 cpu core 1, cpu core 2, cpu core 4 컨테이너를 각각 띄우고, 
동시 추론 할 때 cpu, gpu 사용률 확인
- tx2 장비의 경우 cpu core 1, cpu core 2 컨테이너를 각각 띄우고, 
동시 추론 할 때 cpu, gpu 사용률 확인

**Comment by hyu-leeky** [comment]
응 정애야. 우선은 하나의 pod 컨테이너에서 병렬 추론 작업을 실시한것 같네.
"성능은 docker container에서 추론 했을 때의 성능과 비교하였을때 떨어졌습니다." 이게 어느 정도인지 신경을 쓸 정도로 유의미한지는 모르겠네. 둘이 객관적으로 같은 환경에서 비교가 되었는지도 모르겠어.

tx2 에서 "cpu 6개 까지 모두 사용하도록 on은 할 수 있는데," 이건 무슨 이야기야? 이런 기능이나 설정이 있는거야?

"그래서 최대 3개까지 추론 코드를 멀티로 실행할 수 있을 것이라고 생각" 왜 이렇게 생각을 한거야?

마찬가지로 docker 와 성능 비교는 확인이 어렵고.

to do list 에서는 처음 아이템이 우리가 처음에 확인하고 싶었던것인 만큼 진행을 하고, 2번의 경우 cpu intensive 한걸 gpu 에서 했던 이유는 추론 작업으로는 gpu 를 다 사용하지 못해서인데 지금 보면, gpu 를 충분히 사용하고 있으니 여기서는 굳이 필요하지 않을것 같아.
마지막에 있는 2개 시나리오의 경우, cpu 코어 할당량에 따라서 실제로 추론 처리 성능 throuhgput 을 확인해봐야 할것 같아.

**Comment by jungae-park** [comment]
네 교수님 저도 docker container에서 실행한 실험 결과와 비교를 하는 것이 적당하지 않다고 생각하였습니다. 우선 k8s cluster container에서 실험한 결과를 잘 기록해 두겠습니다.

tx2 장비에서 기본 설치 후 htop으로 확인하면 cpu 개수가 4개밖에 보이지 않는데,
nvpmodel -m 0 의 명령어를 실행하면 숨어져 있던 cpu 2개가 보였습니다.
xavier 장비에서도 기본 설치 후 htop으로 확인하면 cpu 개수가 4개 밖에 안보였는데, 해당 명령어를 실행하니 8개까지 사용 가능해서 tx2도 그런지 확인해보았습니다.
(xavier의 경우 공홈에서 제공하는 spec에는 cpu core가 8개로 나와있습니다.)
그리고 하나의 추론 코드 실행시 cpu를 1000m=1core 사용을 했던 것을 이전에 실험을 통해 확인을 했어서 tx2 장비에서 4개의 cpu core가 있으니, 3개까지는 병령 실행이 될 것이라 생각했습니다.
하지만 memory 부족으로 실제 추론되는 것은 2개밖에 실행되지 않았습니다.

나머지 추가 시나리오에서는 말씀해주신 것처럼 아래와 같이 진행해보겠습니다. 

* 모든 cpu core를 사용하며 가능한 여러개의 컨테이너를 띄우고, 동시 추론 시 cpu, gpu 사용률 확인
* xavier, tx2 장비에서 cpu 코어 할당량에 따라 실체 추론 성능, 처리량 확인

**Comment by hyu-leeky** [comment]
nvpmodel 이 cpu, gpu frequency 등을 동적으로 조정하는 기능이네. 지금 단계에서 굳이 그걸 사용할 필요는 없을것 같아. 지금 목적은 여러 pod 가 gpu 를 공유해서 동시에 사용가능한지를 확인하는게 목적이니까, 그 부분에 촛점을 맞추자.

이 부분역시 핵심 목표에서 벗어나있는 부분인듯 한데 "tx2 장비에서 4개의 cpu core가 있으니, 3개까지는 병령 실행이 될 것이라 생각했습니다." 이런 상황에 왜 3개라고 생각했는지 이해가 잘 안되네. 4개도 아니고. 왜 3개야?

**Comment by jungae-park** [comment]
네 여러 pod 가 gpu 를 공유해서 동시에 사용가능한지를 확인부분 위주로 확인해보겠습니다.

처음에 4개라 생각해서 4개의 추론 코드도 병렬 실행하였는데, 하나의 추론 실행 프로세스만 killed 되고, 3개만 실행되고 있었습니다.
(3개도 마지막에 메모리 부족으로 나머지 하나가 killed 되어 최종 2개만 실행가능했습니다.)
그래서 하나의 추론 코드 실행시 1000m 이상 사용하여 cpu가 4000m 이상 필요하다고 생각되었고, 3개까지는 실행이 가능하지 않을까 생각했던 것입니다.

**Comment by hyu-leeky** [comment]
오케이. 어떤 생각이었는지 알겠다. 이야기할때는 중간 결과라 하더라도 핵심적인 내용 위주로 간결히 하는게 필요할것 같아. 꼭 필요한 내용이라고 핀단된다면 읽는 사람 입장에서 필요한 가정등을 이야기해줘야 할테고. 굳이 그렇지않디면 실험에서도 요약에서도 핵심내용 외에는 쳐내야 시간 효율적으로 작업 할 수 있을것 같아.

**Comment by jungae-park** [comment]
네 교수님 이후 결과 보고 할 때 핵심적인 내용 위주로 정리해서 전달드리겠습니다.

**Comment by jungae-park** [comment]
모든 cpu core를 사용하며 가능한 여러개의 컨테이너를 띄우고, 동시 추론 시 cpu, gpu 사용률 확인 시나리오 실험을 진행하였습니다.

자세한 실험 결과는 아래 노션으로 정리하였습니다.
https://encouraging-lantern-5d1.notion.site/4-b9bf60c2f80242169cbf5e34cda0b118

결론1.
xavier 장비의 경우 10개의 컨테이너를 생성하여 동시 추론이 가능했으며
cpu, memory의 한계에 따라 추가적인 컨테이너 생성 및 동시 추론이 가능해보입니다.
또한 xavier 장비의 경우 10개의 컨테이너에서 동시 추론시 cpu는 최대 7280m, gpu는 최대 98%까지 사용하고 있었습니다.
하나의 컨테이너에서 여러개의 추론 코드를 병렬로 실행하는 것보다 여러 컨테이너를 더 많이 생성하여 추론이 가능하지만 하나의 컨테이너에서 여러개의 추론 코드를 병렬 실행한 것보다 성능이 떨어졌습니다.

결론2.
tx2 장비의 경우 2개의 컨테이너를 생성하여 동시 추론을 진행하였으나,

```bash
command terminated with exit code 137
```
메모리 OOM으로 인해 pod-container를 두개만 띄웠는데에도 위의 해당 메시지를 띄우면서 pod-container가 자동으로 delete 되었습니다.
아래 링크를 통해서 확인해보니 메모리 부족이라고 하여 여러개의 컨테이너 생성시 사용되는 메모리를 조금 더 자세히 확인해보려고 합니다.
https://komodor.com/learn/how-to-fix-oomkilled-exit-code-137/

**Comment by hyu-leeky** [comment]
오케이. 그렇다면 gpu 와 마찬가지로 엣지 장비에서도 여러 컨테이너가 동시에 가속기 장치를 사용할 수 있다는 결론이구나. cpu 할당 크기를 달리할 경우에 성능 차이가 나겠지만 그건 gpu 를 달리 할당해서라기보다는 cpu 를 달리 할당해주기에 성능차이가 날것 같다고 생각이 되네. 이 이슈는 이제 정리하자.

**Comment by jungae-park** [comment]
tx2 장비에서 여러 컨테이너 생성 후 동시 추론시 OOM 에러 해결은 우선 두어도 괜찮을까요?
그리고 cpu 할당 크기를 달리할 경우에 성능 차이가 나겠지만 그건 gpu 를 달리 할당해서라기보다는 cpu 를 달리 할당해주기에 성능차이가 날것 같다고 생각이 되네.
말씀이 맞습니다. 
그럼 xavier, tx2 장비에서 cpu 코어 할당량에 따라 실체 추론 성능, 처리량 확인 시나리오 확인은 추가로 하지 않아도 괜찮을까요?
아니면 해당 이슈는 정리하고 새로 이슈를 생성하여 진행할까요?

**Comment by hyu-leeky** [comment]
cpu 코어 할당량에 따른 실험은 조금 더 진행하면서 꼭 필요하다 싶으면 그때하자. 필요할것 같기는 한데 어떤식으로 필요할런지는 아직 확실치 않으니.

**Comment by jungae-park** [comment]
네 그럼 추후에 다른 시나리오로 실험을 진행하게 될 때 다시 이슈 생성하겠습니다.
