### ISSUE TITLE
workload generator 구현

### ISSUE THREAD

**Issue by jungae-park** [ddps-lab/edge-management-module#19]
엣지 장비에 workload generator를 구현합니다.

**Comment by hyu-leeky** [comment]
@kmu-leeky @jungae-park for tracking

**Comment by jungae-park** [comment]
workload generator 구현을 위한 실험 시나리오를 아래와 같이 구성하여 하나씩 진행해보려고 합니다.

1. 여러 크고 작은 모델을 무작위로 노드에 전달
    1. daemonset yaml 파일을 기준으로 node의 아키텍처가 arm64인 node에 아무 옵션 없이 pod-container 생성
        
        ```jsx
        apiVersion: apps/v1
        kind: DaemonSet
        metadata:
          name: gpu-cpu-daemonset
          namespace: default
        spec:
          selector:
            matchLabels:
              name: gpu-cpu-daemonset
          template:
            metadata:
              labels:
                name: gpu-cpu-daemonset
            spec:
              containers:
              - name: gpu-cpu-1
                image: kmubigdata/edge-inference
                securityContext:
                  privileged: true
                imagePullPolicy: Always      
                command: ['sh', '-c', 'sleep 6000']
              nodeSelector:
                kubernetes.io/arch: arm64
        ```
        
    2. container에서 아래 경우의 수에 따른 추론 진행 후 metric 성능 패턴 분석
        - 모델에 따른 성능 패턴 분석 : mobilenet v1, mobilenet v2, inception v3, yolo v5 (1000장)
        - 배치 추론에 따른 성능 패턴 분석
    3. 리소스 자원 한계에 따른 추론 진행 후 metric 성능 패턴 분석
        - cpu, memory request limit을 달리하여 여러 모델 추론 가능성 파악
        
2. 엣지 노드의 hw spec (CPU, GPU, Memory)에 따라 위에서 분석한 성능 패턴을 기준으로 container 생성 시 cpu, memory request limit을 두고 여러개의 pod-container 생성
    - 여러 크고 작은 모델 추론에서 파악한 패턴에 따라 기준을 세우고 적절한 노드에 전달
    - 최대한 많은 양의 모델 서빙 및 추론

**Comment by hyu-leeky** [comment]
계획은 이제 충분한듯 하니. 진도를 나가보자... 그리고 이 이슈는 워크로드를 생성하는 것과 관련된 내용인데 막상 워크로드가 어떤것일지에 대한 이야기는 없는것 같아. 진행상황을 자주 업데이트 해주면 코멘트 해줄 수 있으니 구체적인 action item 위주로 진행을 해보자. 그리고 이 리포가 퍼블릭인데 연구 관련 이슈 내용이 너무 공개가 되는것 같아서 조금 염려 스럽기도 하다.

**Comment by jungae-park** [comment]
해당 이슈는 다른 이슈에서 다루기 때문에 close 하겠습니다.
