### ISSUE TITLE
tpu 사용량 확인 방법 찾아보기

### ISSUE THREAD

**Issue by jungae-park** [ddps-lab/edge-management-module#2]
https://github.com/ddps-lab/research-issues/issues/45
모델 추론시 tpu 장치를 사용하고 있는지 확인, cpu 사용률과 비교

**Comment by hyu-leeky** [comment]
tpu 사용량 관련해서 조사되는것과 정리되는게 있다면 여기에 코멘트를 남겨줘. 그런게 없다라는 근거가 있는 글이 있다면 그걸 참조해도 좋고. 이건 @unhochoi 도 함께 조사해보자.

**Comment by hyu-leeky** [comment]
온도를 확인하는 방법도 있겠네.

https://coral.ai/docs/pcie-parameters/

연산이 된다면 자연스레 온도가 올라갈테니.

**Comment by jungae-park** [comment]
coral tpu 환경에서 온도를 확인 할 수 있는 파일이 있는지 확인해보았습니다.
https://github.com/google-coral/edgetpu/issues/102
위의 링크를 통해 온도를 확인 할 수 있는 파일을 알 수 있었습니다.
```
cat /sys/class/thermal/thermal_zone0/temp
```
기본 값이 83750였고, 연산시 86185까지 올라가는 것을 확인하였습니다.

다른 방법으로도 온도를 확인 할 수 있을지도 더 찾아보겠습니다.

**Comment by hyu-leeky** [comment]
오케이, 잘 확인했다. 해당 값이 어떤 의미를 가지는지도 한번 파악해보자. 그리고 TPU 작업에 의해서 온도가 올라간다는걸 증명하기 위해서는 cpu 만 사용하는 작업 (예: python 에서 cpu 상에서 행렬 곱셈혹은 무한 루프에서 연산작업등) 을 만들어서 해당 온도 값이 어떻게 변하는지 모니터링해보면 알수 있을것 같아.

**Comment by jungae-park** [comment]
위에서 확인한 온도 값은 라즈베리파이 보드의 온도만 알려줄 뿐, usb coral tpu 온도를 읽을 수 있는 인터페이스가 아닙니다.
* 기본 : 83750 / 1000 = 83°C

따라서 cpu 부하 발생시, tpu 온도를 측정하기 위해 다른 방법을 확인해보고 있으며, 
공식문서에 /sys/class/apex/apex_0 파일을 통해 tpu 온도를 확인 할 수 있다고하여 확인해보았는데, 해당 경로에 파일이 존재하지 않았습니다.
https://coral.ai/docs/pcie-parameters/
![Image](https://user-images.githubusercontent.com/46885199/178180721-1ddf3fb7-5a71-41f5-9b49-2202d6efd4ed.png)

그래서 해당 경로를 활용할 수 있는 방법을 추가적으로 확인해보았는데, 참고할 만한 go 언어로 짜여진 EdgeTPU exporter 자료를 확인하여 사용 방법에 대해 확인하고 있습니다. 
https://github.com/adaptant-labs/edgetpu-exporter/tree/961e0d240e32a4139591cc8725e84f5cbfb80187
tpu 온도를 측정하기에 사용 가능할 만한 정보인지 확인하고 업데이트 하겠습니다.

**Comment by hyu-leeky** [comment]
prometheus edge exporter 좋다.

**Comment by jungae-park** [comment]
1. TPU 온도 측정
(EdgeTPU parometheus Exporter)

- go언어로 짜여져 있고, x86 기반에서 사용 가능
- 추론시 생성되는 파일인가 했지만 아님
- master linux 장비에 usb coral tpu를 부착하여 확인
    - docker install
    [https://jjeongil.tistory.com/1290](https://jjeongil.tistory.com/1290)
    - github에서 제공하는 docker image를 사용하여 container를 생성해 보았지만, 
    container가 생성만 되고 state가 down되어 들어가지지 않음 
    log가 남겨져 있는지 확인하였으나 별다른 내용이 없었음
    - host에서 github의 코드로 온도 파일을 찾으려고 하였지만 go언어로 작성되어 있어 관련된 라이브러리 설치 관련 에러가 계속 발생 (의존성 문제)
    - 온도 파일이 추론시 생성되는 파일인 것인지, tpu를 부착하면 생성되는 파일인지 파악이 되고 있지 않음

2. 전력 측정
power 측정도 파일이 있거나 측정 방법이 따로 나와있지 않음

따라서 다른 방법으로 추가 조사가 필요합니다.

**Comment by jungae-park** [comment]
coral usb tpu 온도 측정값을 spec 제한으로 하드웨어 시스템 상에서 확인을 할 수 없다는 내용입니다.

https://www.qnap.com/en/how-to/faq/article/why-cant-i-see-the-temperature-of-coral-usb-tpu-in-hardware-information

하지만, 아래 이슈를 확인해보면 위의 댓글에서 말씀드린 EdgeTPU Prometheus Exporter이 Coral Dev Board에서는 작동이 되는 것 같습니다.
https://github.com/google-coral/edgetpu/issues/102

** 
(coral dev board : https://coral.ai/products/dev-board/)
**

**Comment by hyu-leeky** [comment]
오케이. 이것도 쉽지 않구나. "cat /sys/class/thermal/thermal_zone0/temp" 이 명령어는 동작을 함? 다른 이슈에서 가능하다고 한것 같은데.

그리고 이 이슈도 research-issues 보다는 ace-edge 에 들어가는 개별 코드 관리 repo 로 들어가는게 맞겠다. 아마도 하드웨어 관리 모듈등으로 들어갈테니 그런 리포가 있으면 util 등의 디렉토리를 만들어서 코드가 들어가게 될듯. 이슈도 옮기는게 맞을것 같아.

**Comment by jungae-park** [comment]
"cat /sys/class/thermal/thermal_zone0/temp" 
해당 명령어는 이 이슈의 위 댓글에서 가능하다고 말씀드린 적이 있습니다.
하지만 이 파일은 TPU의 온도를 측정하는 파일이 아닌, 라즈베리파이 보드의 온도를 측정하는 파일입니다.

**Comment by hyu-leeky** [comment]
아하 오케이. 그러면 해당 파일의 temp 값이 tpu 에서 추론 작업을 할 경우와 rpi cpu 에서 compute intensive 한 작업 (행렬곱셈)을 할 경우 어떻게 다른지 볼수 있을까? 시간이 많이 걸리지 않게 할 수 있다면 해보고, 확인이 어렵다면 tpu 사용량 확인하는건 연구 주제의 메인 토픽은 아니니 결론이 안나더라도 정리하는게 어떨까 싶어.

**Comment by jungae-park** [comment]
* 해당 파일의 temp 값 확인 실험 (tpu에서 추론 작업 vs rpi cpu 부하 발생)

[cpu 부하 발생]
```
from multiprocessing import Pool
from multiprocessing import cpu_count
import signal
 
stop_loop = 0

def exit_chld(x, y):
    global stop_loop
    stop_loop = 1
 
def f(x):
    global stop_loop
    while not stop_loop:
        x*x
  
signal.signal(signal.SIGINT, exit_chld)
 
if __name__ == '__main__':
    processes = cpu_count()
    print('-' * 20)
    print('Running load on CPU(s)')
    print('Utilizing %d cores' % processes)
    print('-' * 20)
    pool = Pool(processes)
    pool.map(f, range(processes))
```

[라즈베리파이의 cpu에 부하를 주었을 때, cpu 사용률 확인]
![image](https://user-images.githubusercontent.com/46885199/184098340-14fec652-52a5-462d-9c12-7937511403a3.png)

[cpu 부하 발생 시 온도 체크]
```
Thu Aug 11 08:47:02 UTC 2022
82289
Thu Aug 11 08:47:07 UTC 2022
85211
Thu Aug 11 08:47:12 UTC 2022
86185
Thu Aug 11 08:47:17 UTC 2022
86185
Thu Aug 11 08:47:22 UTC 2022
85211
Thu Aug 11 08:47:27 UTC 2022
86185
Thu Aug 11 08:47:32 UTC 2022
86672
Thu Aug 11 08:47:38 UTC 2022
86185
Thu Aug 11 08:47:43 UTC 2022
87159
Thu Aug 11 08:47:48 UTC 2022
86672
Thu Aug 11 08:47:53 UTC 2022
83750
Thu Aug 11 08:47:58 UTC 2022
83750
Thu Aug 11 08:48:03 UTC 2022
```

[tpu 추론 작업시 온도 체크]
```
Thu Aug 11 08:39:56 UTC 2022
83263
Thu Aug 11 08:40:01 UTC 2022
83263
Thu Aug 11 08:40:06 UTC 2022
82776
Thu Aug 11 08:40:11 UTC 2022
82776
Thu Aug 11 08:40:16 UTC 2022
83750
Thu Aug 11 08:40:21 UTC 2022
84237
Thu Aug 11 08:40:26 UTC 2022
83750
Thu Aug 11 08:40:31 UTC 2022
84237
Thu Aug 11 08:40:36 UTC 2022
83263
Thu Aug 11 08:40:41 UTC 2022
83263
Thu Aug 11 08:40:46 UTC 2022
81802
Thu Aug 11 08:40:51 UTC 2022
83263
Thu Aug 11 08:40:56 UTC 2022
81315
Thu Aug 11 08:41:01 UTC 2022
82776
Thu Aug 11 08:41:06 UTC 2022
82776
Thu Aug 11 08:41:11 UTC 2022
81802
Thu Aug 11 08:41:16 UTC 2022
82289
Thu Aug 11 08:41:21 UTC 2022
82776
Thu Aug 11 08:41:26 UTC 2022
81315
Thu Aug 11 08:41:31 UTC 2022
82289
Thu Aug 11 08:41:36 UTC 2022
81802
Thu Aug 11 08:41:41 UTC 2022
82776
Thu Aug 11 08:41:46 UTC 2022
81315
Thu Aug 11 08:41:51 UTC 2022
82289
Thu Aug 11 08:41:56 UTC 2022
82289
Thu Aug 11 08:42:01 UTC 2022
81315
Thu Aug 11 08:42:06 UTC 2022
81802
Thu Aug 11 08:42:11 UTC 2022
81802
Thu Aug 11 08:42:16 UTC 2022
82776
Thu Aug 11 08:42:21 UTC 2022
```

1. 해당값은 1/1000 섭씨로 계산되며 예를 들어, 82776일 경우 82°C를 의미합니다.
2. 실험 결과 CPU 부하를 주었을 때 온도가 높아지고, 추론시에는 온도가 높아지는 정도가 적은 것으로 보아,  /sys/class/thermal/thermal_zone0/temp 파일은 라즈베리파이 보드의 온도를 측정하는 것이고 TPU를 활용하여 측정되는 온도를 체크하는 것은 아닌 것 같습니다.

**Comment by hyu-leeky** [comment]
그렇다면 역으로 생각해보면, 우리가 많은 추론 작업을 돌리고 (tpu 에서 작업시킨다는 가정하에), rpi 의 온도를 확인해보면 이게 최소한 cpu 에서 많이 돌아가는지 아닌지 추론을 할수 있지 않을까? tpu 에서 연산이 일어난다면 r-pi 의 cpu 온도가 많이 오르지는 않을테니.

**Comment by jungae-park** [comment]
* 하나의 컨테이너에서 tpu를 사용하며 두개 이상의 추론 작업 불가능
      (하나의 추론 작업에 하나의 tpu 필요)
```
F :1147] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]
Aborted (core dumped)
```
* 여러개의 컨테이너에서 host의 tpu를 공유하며 하나씩 추론 작업 불가능
      (위와 같은 에러 발생 및 여러 컨테이너가 tpu를 공유하지 않음)

* 하나의 컨테이너에서 tpu를 사용하여 하나의 추론 작업을 실행하였을때, 병렬적으로 추론 작업이 진행되며 cpu를 사용하지만 많이 사용하지는 않았습니다.
![image](https://user-images.githubusercontent.com/46885199/184379198-1f7db40b-7d2c-44a0-a548-413b870e0144.png)
그래서 추론 작업시 cpu도 사용하긴 하지만 tpu를 중점으로 사용하기 때문에 cpu 부하시 r-pi의 온도가 오르는 것보다 적게 온도가 오르는 것을 확인 할 수 있습니다.
따라서 r-pi의 온도값으로 추론시 tpu를 잘 사용하고 있다고 할 수 있을 것 같습니다.

**Comment by hyu-leeky** [comment]
응 정애야. 위의 코멘트에 정리한 내용처럼 될것 같아. 혹시 온도 값이 변하는것도 측정을 했으면 같이 공유를 해줄래?

**Comment by jungae-park** [comment]
tpu 추론시 변화한 온도 값은 아래와 같습니다.

```
Thu Aug 11 08:39:56 UTC 2022
83263
Thu Aug 11 08:40:01 UTC 2022
83263
Thu Aug 11 08:40:06 UTC 2022
82776
Thu Aug 11 08:40:11 UTC 2022
82776
Thu Aug 11 08:40:16 UTC 2022
83750
Thu Aug 11 08:40:21 UTC 2022
84237
Thu Aug 11 08:40:26 UTC 2022
83750
Thu Aug 11 08:40:31 UTC 2022
84237
Thu Aug 11 08:40:36 UTC 2022
83263
Thu Aug 11 08:40:41 UTC 2022
83263
Thu Aug 11 08:40:46 UTC 2022
81802
Thu Aug 11 08:40:51 UTC 2022
83263
Thu Aug 11 08:40:56 UTC 2022
81315
Thu Aug 11 08:41:01 UTC 2022
82776
Thu Aug 11 08:41:06 UTC 2022
82776
Thu Aug 11 08:41:11 UTC 2022
81802
Thu Aug 11 08:41:16 UTC 2022
82289
Thu Aug 11 08:41:21 UTC 2022
82776
Thu Aug 11 08:41:26 UTC 2022
81315
Thu Aug 11 08:41:31 UTC 2022
82289
Thu Aug 11 08:41:36 UTC 2022
81802
Thu Aug 11 08:41:41 UTC 2022
82776
Thu Aug 11 08:41:46 UTC 2022
81315
Thu Aug 11 08:41:51 UTC 2022
82289
Thu Aug 11 08:41:56 UTC 2022
82289
Thu Aug 11 08:42:01 UTC 2022
81315
Thu Aug 11 08:42:06 UTC 2022
81802
Thu Aug 11 08:42:11 UTC 2022
81802
Thu Aug 11 08:42:16 UTC 2022
82776
Thu Aug 11 08:42:21 UTC 2022
```

**Comment by hyu-leeky** [comment]
tpu 온도가 이전 코멘트에 있었구나. 땡큐. 이정도면 tpu를 잘 사용한다고 추론이 가능하겠다. 한가지 마지막으로 궁금한건 추론 작업을 rpi 의 cpu 에서 동작하게끔 코드를 수정이 가능할까? 확인은 나중에 천천히 해줘도 괜찮아~

**Comment by jungae-park** [comment]
추론 작업을 rpi 의 cpu 에서 동작하게끔 코드를 수정이 가능한지 살펴보았습니다.

* edgetpu - tflite model을 load하기 위해서는 반드시 tpu 라이브러리의 interpreter에 로드 되어야하며, cpu에서 실행시 아래와 같은 에러 발생합니다.
```bash
RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.
```
* 따라서 양자화된 일반 tflite model (INT8)을 사용해서 온도 변화를 살펴보았고, 양자화된 일반 tflite model (INT8)은 tpu 환경에서 추론을 진행하여도 tpu를 제대로 활용하지 못하고 cpu 환경에서만 추론이 진행되며,
tpu환경에서 추론을 진행하려면 무조건 edgetpu-tflite 모델을 사용해야합니다.
cpu로 동작했기 때문에, cpu 사용률이 증가하고 온도가 크게 오르는 것을 확인하였습니다.
![image](https://user-images.githubusercontent.com/46885199/184816231-cbcf239d-307a-41ed-9792-9ac70199d625.png)
```bash
Tue Aug 16 06:43:01 UTC 2022
88133
Tue Aug 16 06:43:01 UTC 2022
87646
Tue Aug 16 06:43:01 UTC 2022
87159
Tue Aug 16 06:43:01 UTC 2022
86185
Tue Aug 16 06:43:01 UTC 2022
86185
Tue Aug 16 06:43:01 UTC 2022
86185
Tue Aug 16 06:43:01 UTC 2022
85698
Tue Aug 16 06:43:01 UTC 2022
86185
Tue Aug 16 06:43:01 UTC 2022
86672
Tue Aug 16 06:43:01 UTC 2022
86672
Tue Aug 16 06:43:01 UTC 2022
86185
Tue Aug 16 06:43:01 UTC 2022
86672
Tue Aug 16 06:43:01 UTC 2022
86185
Tue Aug 16 06:43:01 UTC 2022
85698
Tue Aug 16 06:43:02 UTC 2022
86185
Tue Aug 16 06:43:02 UTC 2022
85698
Tue Aug 16 06:43:02 UTC 2022
86185
Tue Aug 16 06:43:02 UTC 2022
86672
Tue Aug 16 06:43:02 UTC 2022
86185
Tue Aug 16 06:43:02 UTC 2022
86185
Tue Aug 16 06:43:02 UTC 2022
85698
Tue Aug 16 06:43:02 UTC 2022
86185
Tue Aug 16 06:43:02 UTC 2022
86185
Tue Aug 16 06:43:02 UTC 2022
86672
Tue Aug 16 06:43:02 UTC 2022
86672
Tue Aug 16 06:43:02 UTC 2022
87159
Tue Aug 16 06:43:02 UTC 2022
86672
Tue Aug 16 06:43:02 UTC 2022
86672
Tue Aug 16 06:43:02 UTC 2022
85698
Tue Aug 16 06:43:02 UTC 2022
86672
Tue Aug 16 06:43:02 UTC 2022
87159
```
따라서 기존에 사용하고 있던 edgetpu-tflite 모델은 tpu를 사용하여 추론을 잘하고 있었다고 볼 수 있습니다.

**Comment by hyu-leeky** [comment]
오케이. 내가 이해한 바로는 edgetpu 로 컴파일 된 모델은 cpu 에서 바로 동작이 안되지만, 일반 tflite 모델은 rpi 의 CPU 에서 바로 동작이 가능하다는 거지? 그런 상황에서 tflite 모델을 rpi 의 cpu 에서 동작 시 cpu 활용률도 높고, 온도 역시 올라간다는 거지? edgetpu 에서 작업을 했을때 cpu 온도 변화는 미미했었고? 

그렇다면 한가지 더 궁금증을 가질 수 있는건 tpu 와 cpu 에서 작업 성능을 공평하게 비교해볼수 있을까? 이 주제에 필수적인 내용은 아니겠지만, 자연스럽게 궁금증을 가질 수 있는 부분일것 같아.

**Comment by jungae-park** [comment]
* edgetpu-tflite 모델의 경우, tpu에서만 동작을하고 cpu에서는 동작을 하지 않습니다.
* tflite 모델의 경우는 tpu, cpu에서 모두 동작은 하지만 tpu를 사용하지않고, cpu만 사용하여 사용률이 높고 온도도 높았습니다.

두 모델이 각기 한쪽의 장치에서만 동작을 하고 있는 상황이라,
tpu와 cpu에서 작업 성능을 공평하게 비교하기가 어려울 것 같습니다.

**Comment by hyu-leeky** [comment]
"tflite 모델의 경우는 tpu, cpu에서 모두 동작은 하지만" 이렇다면 tpu, cpu 모두에서 동작 시켜보고 온도,cpu 활용율, 처리 성능등을 비교할 수 있지 않을까?

**Comment by jungae-park** [comment]
네 말씀해주신 내용으로 비교를 해보았었는데,
tflite 모델의 경우는 tpu, cpu에서 모두 동작은 하지만 tpu 환경으로 작업을 돌려도 tpu를 사용하고 있지 않아 cpu 사용률과 온도가 높아졌습니다.
tflite 모델을 cpu환경으로 작업을 했을 때도 마찬가지로 cpu 사용률과 온도가 높아졌습니다.
그래서 tflite 모델은 cpu만을 사용한다는 것을 알게되었고,
tflite 모델의 경우는 tpu와 cpu의 비교보다는 gpu와 cpu의 비교를 하는게 맞을 것 같습니다.

**Comment by hyu-leeky** [comment]
tflite 모델의 경우는 tpu, cpu에서 모두 동작은 하지만 이게 동작이 한다는게 tpu 를 장착한 rpi 에서 동작한다는 이야기구나. 그렇다면 그건 cpu 에서 동작한다고 봐야하는거고.

나라면 이정도까지 했으면 같은 모델에 대해서 edgetpu 로 컴파일 시켜서 tpu 로 동작시 성능, 똑같은 모델을 tflite 로 컴파일해서 rpi cpu 에서 추론 성능, 조금 더 좋은 성능의 CPU 에서 성능 분석 정도까지는 해서, 완전히 공평한 비교는 아닐 수 있겠지만, tpu 의 추론 성능에 대해서 이해를 하는게 어떨까 싶어. 이렇게 하면서 새로운 내용이 발견되고 아이디어가 나오는거니까.. 조금 해보고 안된다고 마무리 해버리면 거기서 큰 발전이 없는 경우가 많거든.

**Comment by jungae-park** [comment]
위의 실험에서 edgetpu-tflite 모델의 경우 기존에 custom 하게 convert 해두었던 inception v3 모델을 사용하였고,
tflite 모델의 경우는 edgetpu로 컴파일러 하기 전 inception v3 모델을 사용하여 tpu와 cpu 장치에서 추론시 온도 변화를 체크하였었습니다.

그렇다면 말씀해주신 내용을 정리하면 edgetpu-tflite (inception v3) 모델을 tpu에서 동작했을 때 성능과 
tflite(inception v3) 모델을 rpi cpu에서 동작했을 때 성능을 비교해서 어떤 것이 더 좋은 성능을 내는지, tpu의 추론 성능에 대한 이해를 좀 더 해보면 좋을 것 같다고 생각하면 좋을까요?

**Comment by hyu-leeky** [comment]
응. 그런식의 내용이 쌓여서 좋은 연구 재료가 되지 않을까 싶어.
inception v3 모델에 대해서, cpu 에서는 tflite 로 변환 된걸로, tpu 에서는 tflite 로 변환 된걸 edge-tpu 로 한번 더 컴파일 후 작업하는거지? 같은 모델 구현에 대해서? 그렇다면 내 생각엔 충분히 비교의 의미가 있을것 같아.

**Comment by jungae-park** [comment]
네 맞습니다. 
그럼 이 이슈는 온도 체크 실행, 결과 파일 이름을 수정한 PR를 머지하여 close하고, 
새롭게 이슈를 생성하여 inception v3 모델에 대해 tpu(edgetpu-tflite)와 rpi-cpu(tflite)의 성능 비교 실험을 진행하고 업데이트하겠습니다.

**Comment by hyu-leeky** [comment]
응 그렇지. 이 이슈는 클로즈하고 새로운 이슈에서 cpu, tpu 비교 괜찮아보인다!
